### ISSUE TITLE
Cant access split data files for TieredImageNet

### ISSUE THREAD

**Issue by chinmayembedded** [Sha-Lab/CASTLE#4]
For miniimagenet, in data folder there are split txt files for train, val, test, etc. 

Can you please provide same files for TieredImageNet? Suggest some logic if there is any.

**Comment by Han-Jia** [comment]
Hi,

The data (npz) file of TieredImageNet is directly split into three parts, meta-train/val/test, which does not need additional split text files.

**Comment by chinmayembedded** [comment]
Thank you. I didn't check downloaded zip.
