### ISSUE TITLE
Accuracies of u->u

### ISSUE THREAD

**Issue by chinmayembedded** [Sha-Lab/CASTLE#5]
Hi, as mentioned in the paper, Table 3 has GFSL accuracies on miniimagenet. The second column 20 unseen categories (u->u). Can you please tell me steps to generate that number for a trained model and a convention used to represent it? I tried eval_gfsl.py but I couldn't get the number. Pease find the red highlighted part.
![doubt](https://user-images.githubusercontent.com/18334906/115201827-a7552300-a0ed-11eb-8095-b6681764023e.png)

**Comment by Han-Jia** [comment]
Hi,

The results of U -> U are similar to the standard few-shot learning (evaluate only on unseen classes) but 20-way tasks are evaluated. Please use eval_fsl.py to get the results.

**Comment by chinmayembedded** [comment]
Thank you so much for confirming!
